# Generated by Django 4.2.15 on 2024-08-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_typename', models.CharField(choices=[('1', 'user'), ('2', 'buyer'), ('3', 'seller'), ('4', 'rent')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_dp', models.ImageField(upload_to='photo')),
                ('u_gender', models.CharField(choices=[('1', 'male'), ('2', 'female')], max_length=10)),
                ('u_email', models.CharField(max_length=10)),
                ('u_phone', models.IntegerField()),
                ('u_status', models.CharField(choices=[('0', 'active'), ('1', 'inactive')], max_length=1)),
                ('u_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.role')),
            ],
        ),
    ]
