# Generated by Django 4.2.15 on 2024-08-31 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_city_complain_details_country_furniture_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_table', models.CharField(max_length=30)),
                ('brand_description', models.TextField()),
                ('brand_logo', models.ImageField(upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='new_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_name', models.CharField(max_length=30)),
                ('furniture_description', models.TextField()),
                ('furniture_price', models.IntegerField()),
                ('furniture_image', models.ImageField(upload_to='photo')),
                ('avalable_quntity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=30)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand_table')),
                ('furniture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.furniture_category')),
            ],
        ),
    ]
