# Generated by Django 4.2.15 on 2024-08-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_avalable_quntity_new_furniture_available_quntity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='old_furniture',
            name='old_furniture_name_f',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.brand_table'),
        ),
        migrations.AlterField(
            model_name='old_furniture',
            name='old_furniture_name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='rent_furniture_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_star_date', models.DateField()),
                ('rent_end_date', models.DateField()),
                ('rent_booking_datetime', models.DateTimeField()),
                ('rent_furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rent_furniture')),
                ('rent_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='old_furniture_buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_booking_datetime', models.DateTimeField()),
                ('old_furniture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.old_furniture')),
                ('user_booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='new_furniture_buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('furniture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.new_furniture')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_detail')),
            ],
        ),
    ]
