# Generated by Django 4.2.15 on 2024-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_old_furniture_old_furniture_name_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain_details',
            name='c_photo',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
